# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259e995eaaa84312b3c9def2fee4baa4c8fcdec15710623e0ad78c512e2f02f8799598d220852d745c6f5583fc587bf54d8e9bde356ace16340ccf45621270c7

test:
  secret_key_base: 7e9c80ea84c54f1a449bd7d2625817405e9bfd5c940fb3af730dfd125a1c2d80c7b42b2a683fb570af1d6398670fe261e350c458c77714db7d3f84dcbe3b32e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
